name: GitHub actions build application
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to build aplications using mvn
branding:
  icon: feather
  color: gray-dark

runs:
  using: "composite"
  steps:
    - name: MVN Package
      shell: bash
      run: mvn -B package --file pom.xml -DskipTests